//! Legal text and version pins.
//!
//! Two documents live here as compiled-in constants: the privacy
//! notice (what phone-home sends) and the terms of use (what a
//! customer agrees to at activation). Both carry a version integer;
//! bumping it forces re-acknowledgment on the next `activate` so a
//! material change to either document is confirmed, not silently
//! carried over.
//!
//! The text is written to be read by the operator. It is not a
//! substitute for counsel-drafted terms, but every claim it makes
//! about behavior is enforced by code:
//!
//! - "opaque license identifier" — `phone_home::license_serial_for`
//!   is an 8-hex HMAC of the key; not reversible.
//! - "does not include hardware fingerprint" — the payload struct
//!   in `phone_home::PhoneHomePayload` has no fingerprint field;
//!   tests verify.
//! - "recorded locally so you can audit" — `phone_home::read_log`
//!   returns every call ever made, signed.
//! - "may revoke your license upon receipt of credible information"
//!   — vendor tooling produces `{"revoked": true}` responses that
//!   the tripwire module acts on.

/// Bumped when the privacy notice text materially changes. Users
/// whose stored `privacy_notice_version` is less than this are
/// re-prompted on next activate.
pub const PRIVACY_NOTICE_VERSION: u32 = 1;

/// Bumped when the terms-of-use text materially changes.
pub const TOU_VERSION: u32 = 1;

pub const PRIVACY_NOTICE: &str = r#"PHANTOM PRIVACY NOTICE (v1)
============================

Phantom performs a periodic license callback ("phone-home") to
verify that your license is still valid. This notice describes
exactly what that call sends and how you can disable it.

WHAT EACH CALL SENDS
--------------------
- An opaque license identifier (an 8-hex HMAC hash of your key;
  your key cannot be recovered from it)
- Your license tier (Free / Pro / Enterprise)
- The Phantom version you are running
- The wall-clock time of the call, in seconds
- A count of any anti-tamper events recorded on this install
- A cryptographic proof-of-possession derived from your license
  key. The endpoint uses it to distinguish a legitimate install
  from an attacker who scraped your license serial.

WHAT EACH CALL DOES NOT SEND
----------------------------
- Your machine hardware fingerprint
- The contents of any profile you have generated
- The seeds you used to generate profiles
- Your name, email, IP address (except as visible at the TCP
  layer to the endpoint), or any other personally identifying
  data Phantom does not need to validate your license

FREQUENCY AND TRANSPORT
-----------------------
- At most once every 24 hours per install
- Sent via the standard `curl` binary on your system so the URL
  and body are visible in `ps` output and any audit log you keep
- Failures (offline, blocked, timeout) do not degrade the tool
- Every call is recorded locally under
  <data_dir>/.phone_home_log so you can audit exactly what was
  sent and when — that file never leaves your machine unless you
  choose to share it

HOW TO DISABLE
--------------
    phantom config set phone_home_enabled false

Disabling means your install will not send license-validation
callbacks. Your license remains valid until it expires; the
endpoint just will not hear from you.
"#;

pub const TOU: &str = r#"PHANTOM TERMS OF USE (v1)
==========================

By activating this license, you agree to the following.

1. USE
   You may use Phantom for personal privacy, legitimate business
   purposes, or authorized security testing.

2. PROHIBITED USE
   You will not use Phantom to conduct financial fraud, to evade a
   lawful court order directed at you, or to facilitate any
   activity that is criminal in the jurisdiction where you
   operate the tool.

3. LICENSE REVOCATION
   Phantom may revoke your license upon receipt of credible
   information that you have breached section 2. Revocation is
   delivered through the phone-home callback (see the Privacy
   Notice) and takes effect on your install's next license load.
   You may appeal by contacting the licensing team.

4. RESPONSE TO LEGAL PROCESS
   Phantom may respond to lawful legal process (subpoena, court
   order, MLAT request) by verifying whether a specific profile
   produced as evidence was generated by a specific license, using
   the `phantom-verify` tool. This capability is limited to
   verifying evidence that has been voluntarily produced or
   lawfully seized. Phantom does not maintain a database of your
   generated profiles.

5. WHAT PHANTOM DOES NOT DO
   Phantom does not silently collect hardware fingerprints,
   profile contents, or personally-identifying data beyond what
   the license issuance flow requires. The full list of what
   phone-home sends is in the Privacy Notice, and every claim
   there is enforced by code.

6. WARRANTY DISCLAIMER
   Phantom is provided "as is" without warranty of any kind, per
   the Proprietary License included in the distribution.
"#;

#[cfg(test)]
mod tests {
    use super::*;

    // Versions are positive and match the ones referenced in text.
    #[test]
    fn versions_are_current() {
        assert_eq!(PRIVACY_NOTICE_VERSION, 1);
        assert_eq!(TOU_VERSION, 1);
        assert!(PRIVACY_NOTICE.contains("(v1)"));
        assert!(TOU.contains("(v1)"));
    }

    // Anchor the enforcement claims: the text makes specific
    // promises the phone_home module implements. If either drifts,
    // these tests break loudly.
    #[test]
    fn privacy_notice_mentions_disable_command() {
        assert!(PRIVACY_NOTICE.contains("phantom config set phone_home_enabled false"));
    }

    #[test]
    fn privacy_notice_promises_no_fingerprint() {
        assert!(
            PRIVACY_NOTICE.contains("does not send") || PRIVACY_NOTICE.contains("DOES NOT SEND")
        );
        assert!(PRIVACY_NOTICE.contains("fingerprint"));
    }

    #[test]
    fn tou_mentions_revocation_and_appeal() {
        assert!(TOU.contains("revoke"));
        assert!(TOU.contains("appeal"));
    }
}
