//! Compile-time obfuscation of the master signing key material.
//!
//! This file is compiled and executed by the build system BEFORE the crate
//! itself. Its ONLY output is `$OUT_DIR/master_key_obf.rs` containing the
//! XOR-scrambled bytes and a version marker. The plaintext master key
//! (below) is NOT baked into the shipping binary — only the scrambled
//! output is.
//!
//! An attacker with the binary sees:
//!   - a 32-byte array of noise (`OBFUSCATED_MASTER`) in the .rodata section
//!   - the unscrambling code (`derive_xor_byte`) inlined at each call site
//!
//! They must run both to reconstruct the master key, versus simply piping
//! the binary through `strings` today.
//!
//! To rotate the master key: change `MASTER_SEED` below AND every previously
//! issued license key becomes invalid. Do not rotate lightly.

fn derive_xor_byte(i: usize) -> u8 {
    // Deliberately non-obvious mixing function. Must match the runtime
    // reader in `src/keys.rs` exactly, byte-for-byte.
    const A: u32 = 0xA5F3_7B24;
    const B: u32 = 0x9E3E_1C71;
    const C: u32 = 0x4B27_D9A6;

    let i32_ = i as u32;
    let rot = A.rotate_left(i32_ & 31);
    let sum = rot.wrapping_add(B.wrapping_mul(i32_.wrapping_add(17)));
    let mix = sum ^ C.rotate_right((i32_ * 3) & 31);
    ((mix >> ((i32_ & 3) * 8)) & 0xFF) as u8
}

fn main() {
    // 32 bytes of high-entropy material picked out of band. This value is
    // the ONLY thing that authenticates a license key; if it ever leaks,
    // every issued license can be forged. Keep it out of chat logs, PR
    // descriptions, and any process that might mirror this file publicly.
    const MASTER_SEED: [u8; 32] = [
        0x8f, 0x2e, 0xa7, 0x13, 0xb6, 0x5c, 0xd1, 0x9a, 0x74, 0x08, 0x3b, 0xef, 0x51, 0xc4, 0x2d,
        0x7f, 0x96, 0x1a, 0x83, 0x5e, 0xd0, 0x67, 0x2b, 0x4c, 0x91, 0xac, 0x38, 0xe7, 0xf5, 0x0d,
        0x62, 0x89,
    ];

    let mut obfuscated = [0u8; 32];
    for (i, b) in MASTER_SEED.iter().enumerate() {
        obfuscated[i] = b ^ derive_xor_byte(i);
    }

    let mut src = String::with_capacity(512);
    src.push_str("// AUTO-GENERATED by build.rs — do not edit.\n");
    src.push_str("// Byte-for-byte XOR-obfuscation of the master signing key.\n");
    src.push_str("pub(crate) const OBFUSCATED_MASTER: [u8; 32] = [\n    ");
    for (i, b) in obfuscated.iter().enumerate() {
        src.push_str(&format!("0x{:02x}, ", b));
        if (i + 1) % 8 == 0 {
            src.push_str("\n    ");
        }
    }
    src.push_str("\n];\n");
    // Version byte lets us flip generations later without changing the
    // OBFUSCATED_MASTER shape.
    src.push_str("pub(crate) const MASTER_KEY_GEN: u8 = 1;\n");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR must be set by cargo");
    let dest = std::path::Path::new(&out_dir).join("master_key_obf.rs");
    std::fs::write(&dest, src).expect("write master_key_obf.rs");

    println!("cargo:rerun-if-changed=build.rs");
}
